DROP TABLE IF EXISTS users, films, friends, likes, film_genres, MPA,
    genres cascade ;

CREATE TABLE IF NOT EXISTS USERS (
                                     user_id INT PRIMARY KEY AUTO_INCREMENT,
                                     email VARCHAR NOT NULL,
                                     login VARCHAR NOT NULL,
                                     user_name VARCHAR NOT NULL,
                                     birthday DATE
);
CREATE TABLE IF NOT EXISTS MPA (
                                   mpa_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   mpa_name VARCHAR
);
CREATE TABLE IF NOT EXISTS FILMS (
                                     film_id INT PRIMARY KEY AUTO_INCREMENT,
                                     film_name VARCHAR NOT NULL,
                                     description VARCHAR,
                                     duration INT NOT NULL,
                                     mpa_id INT NOT NULL REFERENCES MPA(mpa_id),
                                     release_date DATE
);
CREATE TABLE IF NOT EXISTS GENRES (
                                      genre_id INT PRIMARY KEY AUTO_INCREMENT,
                                      genre_name VARCHAR
);
CREATE TABLE IF NOT EXISTS FILM_GENRES (
                                           film_id INT REFERENCES FILMS(film_id) ON DELETE CASCADE,
                                           genre_id INT REFERENCES GENRES(genre_id) ON DELETE CASCADE,
                                           PRIMARY KEY(film_id, genre_id)
);
CREATE TABLE IF NOT EXISTS LIKES (
                                     user_id INT REFERENCES USERS(user_id) ON DELETE CASCADE,
                                     film_id INT REFERENCES FILMS(film_id) ON DELETE CASCADE,
                                     PRIMARY KEY(user_id, film_id)
);
CREATE TABLE IF NOT EXISTS FRIENDS (
                                       id INT PRIMARY KEY AUTO_INCREMENT,
                                       user_id INT REFERENCES USERS(user_id) ON DELETE CASCADE,
                                       friend_id INT REFERENCES USERS(user_id) ON DELETE CASCADE,
                                       status BOOLEAN
);