create table if not exists mpa_ratings
(
    id   integer generated by default as identity primary key,
    name varchar(5)
);

create table if not exists films
(
    id           integer generated by default as identity primary key,
    name         varchar(50),
    description  varchar(200),
    release_date date,
    duration     integer,
    mpa          integer references mpa_ratings (id)
);

create table if not exists genres
(
    id   integer generated by default as identity primary key,
    name varchar(14)
);

create table if not exists films_genres
(
    film_id  int references films (id),
    genre_id int references genres (id),
    primary key (film_id, genre_id)
);

create table if not exists users
(
    id       integer generated by default as identity primary key,
    email    varchar(20),
    login    varchar(20),
    name     varchar(20),
    birthday date
);

create table if not exists likes
(
    film_id int references films (id),
    user_id int references users (id),
    primary key (film_id, user_id)
);

create table if not exists friends
(
    user_id   int references users (id),
    friend_id int references users (id),
    primary key (user_id, friend_id)
);